version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=codex_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=khan123
  web:
    restart: always
    #you will be able to “keep the container running”.
    tty: true
    build: .
#    command: python manage.py runserver
    volumes:
      - ./:/docker_codex/
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      - POSTGRES_NAME=codex_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=khan123
    depends_on:
      - db