# Generated by Django 3.0.6 on 2022-03-15 06:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subjects')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subject_tbl_dm',
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200, null=True)),
                ('topic_order', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='topics')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Subjects')),
            ],
            options={
                'verbose_name': 'Subject Topics',
                'verbose_name_plural': 'Subjects Topics',
                'db_table': 'topics_tbl_dm',
            },
        ),
        migrations.CreateModel(
            name='TopicSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200, null=True)),
                ('topic_order', models.IntegerField(default=1)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Topics')),
            ],
            options={
                'verbose_name': 'Topic Section',
                'verbose_name_plural': 'Topic Section',
                'db_table': 'topic_section_tbl',
            },
        ),
    ]
