# Generated by Django 3.0.6 on 2022-03-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20220315_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='slug',
            field=models.SlugField(default='pppp', max_length=120),
        ),
    ]
