# syntax=docker/dockerfile:1
FROM python:3.8-slim-buster
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV WEBAPP_DIR=/usr/src/codex

RUN mkdir -p /var/log/gunicorn

WORKDIR $WEBAPP_DIR
# copy project
Copy . .

# install psycopg2 dependencies
#RUN apt update && apt install postgresql-dev gcc python3-dev musl-dev
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

