
FROM python:3.9.6-alpine as builder
# set work directory
WORKDIR /usr/src/codex

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# lint
RUN pip install --upgrade pip
RUN pip install flake8==3.9.2
COPY . .
RUN flake8 --ignore=E501,F401 .

# install dependencies
COPY ./requirements.txt .
RUN pip install -r requirements.txt


#########
# FINAL #
#########


# pull official base image
FROM python:3.9.6-alpine

RUN mkdir -p /home/codex

# create the app user
RUN addgroup -S codex && adduser -S codex -G codex


# create the appropriate directories

ENV APP_HOME=/home/codex
RUN mkdir $APP_HOME/staticfiles
WORKDIR $APP_HOME


# install dependencies
#RUN apk update && apk add libpq
#COPY --from=builder /usr/src/codex/wheels /wheels
#COPY --from=builder /usr/src/codex/requirements.txt .
#RUN pip install --no-cache /wheels/*

# copy entrypoint.prod.sh
#COPY ./entrypoint.prod.sh .
#RUN sed -i 's/\r$//g'  $APP_HOME/entrypoint.prod.sh
#RUN chmod +x  $APP_HOME/entrypoint.prod.sh

# copy project
COPY . $APP_HOME

# chown all the files to the app user
RUN chown -R codex:codex $APP_HOME

# change to the app user
USER codex
EXPOSE 8000
CMD exec gunicorn codex.wsgi:application — bind 0.0.0.0:8000 — workers 3

