#This denotes that we are using version 3 of Docker Compose, and Docker will provide the appropriate features.
version: "3.9"

services:
    db:
      image: postgres:13.0-alpine
      volumes:
        - ./data/db:/var/lib/postgresql/data
      env_file:
        - ./.env.prod.db
    web:
      restart: always
      tty: true
      build:
        context: ./
        dockerfile: Dockerfile.prod
#      command: gunicorn codex.wsgi:application --bind 0.0.0.0:8000
      volumes:
        - static_volume:/home/codex/web/staticfiles
      expose:
        - 8000
      env_file:
        - ./.env.prod
      depends_on:
        - db

    nginx:
      build: ./nginx
      ports:
        - 1337:80
      volumes:
        - static_volume:/home/codex/web/staticfiles
      depends_on:
        - web
#volumes needs to be at the same indentation with services
volumes:
  static_volume: